### ISSUE TITLE
Error when creating cold/hot observable with values

### ISSUE THREAD

**Issue by meltedspark** [meltedspark/jest-marbles#22]
**Version**: 1.1.1
**Issue**: when expected observable is cold/hot observable with values object, the test fails with exception:

```
RangeError: Invalid count value
    at String.repeat (native)
    at Function../index.ts.Marblizer.marblize (.../node_modules/jest-marbles/umd/webpack:/JestMarbles/src/marblizer.ts:14:56)
    at Object.toBeNotifications (.../node_modules/jest-marbles/umd/webpack:/JestMarbles/src/jest/custom-matchers.ts:9:36)
    at Object.throwingMatcher [as toBeNotifications] (.../node_modules/expect/build/index.js:214:24)
    at TestScheduler.assertDeepEqual (.../node_modules/jest-marbles/umd/webpack:/JestMarbles/src/rxjs/assert-deep-equal.ts:29:20)
    at TestScheduler../node_modules/rxjs/testing/TestScheduler.js.TestScheduler.flush (.../node_modules/jest-marbles/umd/webpack:/JestMarbles/node_modules/rxjs/testing/TestScheduler.js:118:1)
    at Object.<anonymous> (.../node_modules/jest-marbles/umd/webpack:/JestMarbles/index.ts:65:19)
    at Object.asyncFn (.../node_modules/jest-jasmine2/build/jasmine_async.js:51:37)
    at e (.../node_modules/jest-jasmine2/build/queue_runner.js:52:12)
    at mapper (.../node_modules/jest-jasmine2/build/queue_runner.js:39:19)
    at promise.then (.../node_modules/jest-jasmine2/build/queue_runner.js:73:82)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```
**Steps to reproduce**:

1. Run the following test:

```
  it('Should work', () => {
    const expected = cold('--e-|', {e: {coolProperty: 1}});
    expect(expected).toBeObservable(expected);
  })
```

**Comment by meltedspark** [comment]
Will take some time to fix, meanwhile use version **1.0.6**
